name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]

jobs:
  vercel_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: vercel/action@v2
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          # Team slug/Org identifier (provided)
          vercel-org-id: "dawits-projects-866ea979"
          # Project ID (provided)
          vercel-project-id: "prj_gYNQxmE4uO90HTNgGSdCzVjXhh6X"
          vercel-args: '--prod'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
